-- 数据库更新脚本V2：添加约束规则表和编码记录表扩展字段
USE mdm_db;

-- 约束规则表
CREATE TABLE IF NOT EXISTS MDM_MODEL_CONSTRAINT (
    ID VARCHAR(32) NOT NULL PRIMARY KEY,
    MODEL_ID VARCHAR(32) NOT NULL,
    CONSTRAINT_TYPE VARCHAR(30) NOT NULL COMMENT '唯一约束/关联约束-上下限/关联约束-组必填/关联约束-主从必填/关联约束-关联引用/关联约束-自定义表达式',
    CONSTRAINT_NAME VARCHAR(120) NOT NULL,
    CONSTRAINT_CODE VARCHAR(60),
    SEVERITY VARCHAR(20) DEFAULT '错误' COMMENT '错误/警告',
    SCOPE VARCHAR(30) DEFAULT '全部' COMMENT '全部/类别/当前主数据',
    CONDITION_EXPR TEXT COMMENT '条件表达式',
    CONFIG_JSON TEXT COMMENT 'JSON格式详细配置',
    STATUS VARCHAR(12) DEFAULT '启用',
    SORT_ORDER INT DEFAULT 0,
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IS_DELETED TINYINT DEFAULT 0,
    FOREIGN KEY (MODEL_ID) REFERENCES MDM_DATA_MODEL(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 编码记录表添加SEGMENT_ID和PREFIX字段（用于序列号并发安全）
SET @dbname = DATABASE();
SET @tablename = 'MDM_CODE_RECORD';

-- 添加 SEGMENT_ID 列
SET @columnname = 'SEGMENT_ID';
SET @preparedStatement = (SELECT IF(
  (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
   WHERE TABLE_SCHEMA = @dbname AND TABLE_NAME = @tablename AND COLUMN_NAME = @columnname) > 0,
  'SELECT 1',
  'ALTER TABLE MDM_CODE_RECORD ADD COLUMN SEGMENT_ID VARCHAR(32) AFTER SCHEME_ID'
));
PREPARE alterIfNotExists FROM @preparedStatement;
EXECUTE alterIfNotExists;
DEALLOCATE PREPARE alterIfNotExists;

-- 添加 PREFIX 列
SET @columnname = 'PREFIX';
SET @preparedStatement = (SELECT IF(
  (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
   WHERE TABLE_SCHEMA = @dbname AND TABLE_NAME = @tablename AND COLUMN_NAME = @columnname) > 0,
  'SELECT 1',
  'ALTER TABLE MDM_CODE_RECORD ADD COLUMN PREFIX VARCHAR(255) AFTER SEGMENT_ID'
));
PREPARE alterIfNotExists FROM @preparedStatement;
EXECUTE alterIfNotExists;
DEALLOCATE PREPARE alterIfNotExists;

-- 添加唯一索引以保证并发安全
CREATE INDEX IF NOT EXISTS IDX_CODE_RECORD_SCHEME_SEG_PREFIX ON MDM_CODE_RECORD(SCHEME_ID, SEGMENT_ID, PREFIX);
