USE mdm_db;

-- 用户信息表
CREATE TABLE IF NOT EXISTS BASE_USER (
    ID VARCHAR(20) NOT NULL PRIMARY KEY,
    USERNAME VARCHAR(60),
    PASSWORD VARCHAR(96),
    NICKNAME VARCHAR(60),
    SEX VARCHAR(36),
    ORGID VARCHAR(20),
    ORGNAME VARCHAR(270),
    BIRTHDAY DATE,
    EMAIL VARCHAR(120),
    PHONE VARCHAR(30),
    STATUS VARCHAR(12),
    SECURITY_LEVEL VARCHAR(36),
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 单位信息表
CREATE TABLE IF NOT EXISTS BASE_ORG (
    ID VARCHAR(20) NOT NULL PRIMARY KEY,
    ORGNAME VARCHAR(270),
    PARENTID VARCHAR(20),
    STATUS VARCHAR(12),
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 角色信息表
CREATE TABLE IF NOT EXISTS BASE_ROLE (
    ID VARCHAR(32) NOT NULL PRIMARY KEY,
    ROLE_CODE VARCHAR(30) NOT NULL UNIQUE,
    ROLE_NAME VARCHAR(60) NOT NULL UNIQUE,
    ORGID VARCHAR(20),
    STATUS VARCHAR(12),
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 用户组信息表
CREATE TABLE IF NOT EXISTS BASE_GROUP (
    ID VARCHAR(32) NOT NULL PRIMARY KEY,
    GROUP_CODE VARCHAR(60) NOT NULL UNIQUE,
    GROUP_NAME VARCHAR(120) NOT NULL UNIQUE,
    ORGID VARCHAR(20),
    STATUS VARCHAR(12),
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 用户角色关联表
CREATE TABLE IF NOT EXISTS BASE_USER_ROLE (
    ID VARCHAR(32) NOT NULL PRIMARY KEY,
    USER_ID VARCHAR(20),
    ROLE_ID VARCHAR(32),
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 用户用户组关联表
CREATE TABLE IF NOT EXISTS BASE_USER_GROUP (
    ID VARCHAR(32) NOT NULL PRIMARY KEY,
    USER_ID VARCHAR(20),
    GROUP_ID VARCHAR(32),
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 角色用户组关联表
CREATE TABLE IF NOT EXISTS BASE_ROLE_GROUP (
    ID VARCHAR(32) NOT NULL PRIMARY KEY,
    ROLE_ID VARCHAR(32),
    GROUP_ID VARCHAR(32),
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 数据模型表
CREATE TABLE IF NOT EXISTS MDM_DATA_MODEL (
    ID VARCHAR(32) NOT NULL PRIMARY KEY,
    MODEL_CODE VARCHAR(60) NOT NULL UNIQUE,
    MODEL_NAME VARCHAR(120) NOT NULL,
    MODEL_TYPE VARCHAR(20),
    VERSION INT DEFAULT 1,
    STATUS VARCHAR(20),
    ORGID VARCHAR(20),
    DESCRIPTION TEXT,
    CREATE_BY VARCHAR(20),
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IS_DELETED TINYINT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 模型属性表
CREATE TABLE IF NOT EXISTS MDM_MODEL_ATTRIBUTE (
    ID VARCHAR(32) NOT NULL PRIMARY KEY,
    MODEL_ID VARCHAR(32),
    ATTRIBUTE_CODE VARCHAR(60) NOT NULL,
    ATTRIBUTE_NAME VARCHAR(120) NOT NULL,
    DATA_TYPE VARCHAR(30),
    IS_REQUIRED TINYINT DEFAULT 0,
    MAX_LENGTH INT,
    DEFAULT_VALUE VARCHAR(255),
    DISPLAY_TYPE VARCHAR(20),
    SORT_ORDER INT DEFAULT 0,
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IS_DELETED TINYINT DEFAULT 0,
    FOREIGN KEY (MODEL_ID) REFERENCES MDM_DATA_MODEL(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 主数据业务表
CREATE TABLE IF NOT EXISTS MDM_MAIN_DATA (
    ID VARCHAR(32) NOT NULL PRIMARY KEY,
    MODEL_ID VARCHAR(32),
    CODE VARCHAR(60),
    VERSION INT DEFAULT 1,
    FLOW_STATUS VARCHAR(20),
    DATA_STATUS VARCHAR(20),
    JSON_DATA TEXT,
    CREATED_BY_ID VARCHAR(20),
    CREATED_BY_NAME VARCHAR(60),
    CREATED_BY_ORGID VARCHAR(20),
    SUBMITTED_BY_ORGID VARCHAR(20),
    MODIFIED_BY_ID VARCHAR(20),
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    MODIFY_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IS_MODIFY TINYINT DEFAULT 0,
    SECURITY_LEVEL VARCHAR(36),
    IS_DELETED TINYINT DEFAULT 0,
    FOREIGN KEY (MODEL_ID) REFERENCES MDM_DATA_MODEL(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 编码规则表
CREATE TABLE IF NOT EXISTS MDM_CODE_RULE (
    ID VARCHAR(32) NOT NULL PRIMARY KEY,
    RULE_CODE VARCHAR(60) NOT NULL UNIQUE,
    RULE_NAME VARCHAR(120) NOT NULL,
    ORGID VARCHAR(20),
    STATUS VARCHAR(12),
    CREATE_BY VARCHAR(20),
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IS_DELETED TINYINT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 编码方案表
CREATE TABLE IF NOT EXISTS MDM_CODE_SCHEME (
    ID VARCHAR(32) NOT NULL PRIMARY KEY,
    RULE_ID VARCHAR(32),
    SCHEME_CODE VARCHAR(60) NOT NULL,
    SCHEME_NAME VARCHAR(120) NOT NULL,
    CONDITION_EXPRESSION TEXT,
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IS_DELETED TINYINT DEFAULT 0,
    FOREIGN KEY (RULE_ID) REFERENCES MDM_CODE_RULE(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 编码段表
CREATE TABLE IF NOT EXISTS MDM_CODE_SEGMENT (
    ID VARCHAR(32) NOT NULL PRIMARY KEY,
    SCHEME_ID VARCHAR(32),
    SEGMENT_CODE VARCHAR(60) NOT NULL,
    SEGMENT_NAME VARCHAR(120) NOT NULL,
    SEGMENT_TYPE VARCHAR(30),
    SEGMENT_FORMAT VARCHAR(120),
    SEGMENT_VALUE VARCHAR(255),
    FIXED_VALUE VARCHAR(255),
    SORT_ORDER INT DEFAULT 0,
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IS_DELETED TINYINT DEFAULT 0,
    FOREIGN KEY (SCHEME_ID) REFERENCES MDM_CODE_SCHEME(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 编码记录表
CREATE TABLE IF NOT EXISTS MDM_CODE_RECORD (
    ID VARCHAR(32) NOT NULL PRIMARY KEY,
    SCHEME_ID VARCHAR(32),
    CURRENT_VALUE BIGINT DEFAULT 0,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (SCHEME_ID) REFERENCES MDM_CODE_SCHEME(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 工作流定义表
CREATE TABLE IF NOT EXISTS MDM_WORKFLOW (
    ID VARCHAR(32) NOT NULL PRIMARY KEY,
    WORKFLOW_CODE VARCHAR(60) NOT NULL UNIQUE,
    WORKFLOW_NAME VARCHAR(120) NOT NULL,
    WORKFLOW_TYPE VARCHAR(20),
    ORGID VARCHAR(20),
    STATUS VARCHAR(12),
    DEFINITION TEXT,
    CREATE_BY VARCHAR(20),
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IS_DELETED TINYINT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 工作流实例表
CREATE TABLE IF NOT EXISTS MDM_WORKFLOW_INSTANCE (
    ID VARCHAR(32) NOT NULL PRIMARY KEY,
    WORKFLOW_ID VARCHAR(32),
    BUSINESS_ID VARCHAR(32),
    BUSINESS_TYPE VARCHAR(30),
    CURRENT_NODE VARCHAR(60),
    STATUS VARCHAR(20),
    INITIATOR_ID VARCHAR(20),
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IS_DELETED TINYINT DEFAULT 0,
    FOREIGN KEY (WORKFLOW_ID) REFERENCES MDM_WORKFLOW(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 数据分发表
CREATE TABLE IF NOT EXISTS MDM_ESB_MODEL (
    ID VARCHAR(32) NOT NULL PRIMARY KEY,
    MODEL_CODE VARCHAR(60) NOT NULL,
    MODEL_NAME VARCHAR(120) NOT NULL,
    MODEL_TYPE VARCHAR(20),
    ORGID VARCHAR(20),
    STATUS VARCHAR(12),
    CREATE_BY VARCHAR(20),
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IS_DELETED TINYINT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 插入初始数据
INSERT INTO BASE_ORG (ID, ORGNAME, PARENTID, STATUS) VALUES
('ROOT', '集团总部', NULL, '启用'),
('ORG001', '研发中心', 'ROOT', '启用'),
('ORG002', '销售中心', 'ROOT', '启用');

INSERT INTO BASE_USER (ID, USERNAME, PASSWORD, NICKNAME, SEX, ORGID, ORGNAME, EMAIL, PHONE, STATUS) VALUES
('admin', 'admin', 'admin', '系统管理员', '男', 'ROOT', '集团总部', 'admin@maike.com', '13800138000', '启用'),
('user001', 'data_mgr', '123456', '数据管理员', '女', 'ORG001', '研发中心', 'data_mgr@maike.com', '13800138001', '启用');

INSERT INTO BASE_ROLE (ID, ROLE_CODE, ROLE_NAME, ORGID, STATUS) VALUES
('role001', 'ROLE_ADMIN', '运维管理员', 'ROOT', '启用'),
('role002', 'ROLE_DATA_ADMIN', '数据管理员', 'ORG001', '启用'),
('role003', 'ROLE_AUDITOR', '审核人', 'ORG001', '启用'),
('role004', 'ROLE_APPLICANT', '申请人', 'ORG001', '启用');

INSERT INTO BASE_GROUP (ID, GROUP_CODE, GROUP_NAME, ORGID, STATUS) VALUES
('group001', 'GROUP_ADMIN', '管理员组', 'ROOT', '启用'),
('group002', 'GROUP_DATA', '数据管理组', 'ORG001', '启用');

INSERT INTO BASE_USER_ROLE (ID, USER_ID, ROLE_ID) VALUES
('ur001', 'admin', 'role001'),
('ur002', 'user001', 'role002');

INSERT INTO BASE_USER_GROUP (ID, USER_ID, GROUP_ID) VALUES
('ug001', 'admin', 'group001'),
('ug002', 'user001', 'group002');

INSERT INTO MDM_DATA_MODEL (ID, MODEL_CODE, MODEL_NAME, MODEL_TYPE, VERSION, STATUS, ORGID, CREATE_BY, DESCRIPTION) VALUES
('model001', 'SUPPLIER', '供应商模型', '普通模型', 1, '已发布', 'ROOT', 'admin', '供应商主数据管理'),
('model002', 'CUSTOMER', '客户模型', '普通模型', 1, '已发布', 'ROOT', 'admin', '客户主数据管理'),
('model003', 'PRODUCT', '产品模型', '普通模型', 1, '编制中', 'ORG001', 'user001', '产品主数据管理');

INSERT INTO MDM_MODEL_ATTRIBUTE (ID, MODEL_ID, ATTRIBUTE_CODE, ATTRIBUTE_NAME, DATA_TYPE, IS_REQUIRED, MAX_LENGTH, DISPLAY_TYPE, SORT_ORDER) VALUES
('attr001', 'model001', 'SUPPLIER_CODE', '供应商编码', 'VARCHAR', 1, 60, '文本', 1),
('attr002', 'model001', 'SUPPLIER_NAME', '供应商名称', 'VARCHAR', 1, 120, '文本', 2),
('attr003', 'model001', 'CONTACT_PERSON', '联系人', 'VARCHAR', 0, 60, '文本', 3),
('attr004', 'model001', 'PHONE', '联系电话', 'VARCHAR', 0, 30, '文本', 4),
('attr005', 'model001', 'ADDRESS', '地址', 'VARCHAR', 0, 255, '文本', 5),
('attr006', 'model002', 'CUSTOMER_CODE', '客户编码', 'VARCHAR', 1, 60, '文本', 1),
('attr007', 'model002', 'CUSTOMER_NAME', '客户名称', 'VARCHAR', 1, 120, '文本', 2),
('attr008', 'model002', 'CONTACT_PERSON', '联系人', 'VARCHAR', 0, 60, '文本', 3),
('attr009', 'model002', 'PHONE', '联系电话', 'VARCHAR', 0, 30, '文本', 4),
('attr010', 'model003', 'PRODUCT_CODE', '产品编码', 'VARCHAR', 1, 60, '文本', 1),
('attr011', 'model003', 'PRODUCT_NAME', '产品名称', 'VARCHAR', 1, 120, '文本', 2),
('attr012', 'model003', 'PRODUCT_TYPE', '产品类型', 'VARCHAR', 0, 60, '下拉', 3);

INSERT INTO MDM_MAIN_DATA (ID, MODEL_ID, CODE, VERSION, FLOW_STATUS, DATA_STATUS, CREATED_BY_ID, CREATED_BY_NAME, CREATED_BY_ORGID, SECURITY_LEVEL) VALUES
('data001', 'model001', 'SUP202401001', 1, 'DONE', '审核通过', 'admin', '系统管理员', 'ROOT', '普通'),
('data002', 'model001', 'SUP202401002', 1, 'DONE', '审核通过', 'admin', '系统管理员', 'ROOT', '普通'),
('data003', 'model002', 'CUS202401001', 1, 'DONE', '审核通过', 'admin', '系统管理员', 'ROOT', '普通'),
('data004', 'model001', 'SUP202401003', 1, 'IN_PROGRESS', '审核中', 'user001', '数据管理员', 'ORG001', '普通');

INSERT INTO MDM_WORKFLOW (ID, WORKFLOW_CODE, WORKFLOW_NAME, WORKFLOW_TYPE, ORGID, STATUS, CREATE_BY, DEFINITION) VALUES
('wf001', 'WF_SUPPLIER', '供应商审核流程', '数据审核', 'ROOT', '启用', 'admin', '{"nodes":[{"id":"start","type":"start"},{"id":"audit1","type":"task","assignee":"审核人"},{"id":"end","type":"end"}]}'),
('wf002', 'WF_CUSTOMER', '客户审核流程', '数据审核', 'ROOT', '启用', 'admin', '{"nodes":[{"id":"start","type":"start"},{"id":"audit1","type":"task","assignee":"审核人"},{"id":"end","type":"end"}]}');

INSERT INTO MDM_CODE_RULE (ID, RULE_CODE, RULE_NAME, ORGID, STATUS, CREATE_BY) VALUES
('rule001', 'RULE_SUPPLIER', '供应商编码规则', 'ROOT', '启用', 'admin'),
('rule002', 'RULE_CUSTOMER', '客户编码规则', 'ROOT', '启用', 'admin');

INSERT INTO MDM_CODE_SCHEME (ID, RULE_ID, SCHEME_CODE, SCHEME_NAME, CONDITION_EXPRESSION) VALUES
('scheme001', 'rule001', 'SCHEME_SUPPLIER', '供应商编码方案', NULL),
('scheme002', 'rule002', 'SCHEME_CUSTOMER', '客户编码方案', NULL);

INSERT INTO MDM_CODE_SEGMENT (ID, SCHEME_ID, SEGMENT_CODE, SEGMENT_NAME, SEGMENT_TYPE, SEGMENT_FORMAT, FIXED_VALUE, SORT_ORDER) VALUES
('seg001', 'scheme001', 'SEG_PREFIX', '前缀', 'FIXED', NULL, 'SUP', 1),
('seg002', 'scheme001', 'SEG_YEAR', '年份', 'TIMESTAMP', 'yyyy', NULL, 2),
('seg003', 'scheme001', 'SEG_SEQ', '流水号', 'SEQUENCE', '000', NULL, 3),
('seg004', 'scheme002', 'SEG_PREFIX', '前缀', 'FIXED', NULL, 'CUS', 1),
('seg005', 'scheme002', 'SEG_YEAR', '年份', 'TIMESTAMP', 'yyyy', NULL, 2),
('seg006', 'scheme002', 'SEG_SEQ', '流水号', 'SEQUENCE', '000', NULL, 3);

INSERT INTO MDM_ESB_MODEL (ID, MODEL_CODE, MODEL_NAME, MODEL_TYPE, ORGID, STATUS, CREATE_BY) VALUES
('esb001', 'ESB_SUPPLIER_PUSH', '供应商数据推送', '分发', 'ROOT', '启用', 'admin');
