USE mdm_db;

-- =============================================
-- 编码规则引擎扩展 - 新增段类型支持字段
-- =============================================

-- 编码段表新增字段
ALTER TABLE MDM_CODE_SEGMENT ADD COLUMN SEGMENT_LENGTH INT DEFAULT NULL COMMENT '段长度(用于UUID截取、首字母流水等)';
ALTER TABLE MDM_CODE_SEGMENT ADD COLUMN EXPRESSION TEXT DEFAULT NULL COMMENT '表达式(SQL表达式/层级码JSON配置等)';
ALTER TABLE MDM_CODE_SEGMENT ADD COLUMN REFERENCE_FIELD VARCHAR(255) DEFAULT NULL COMMENT '引用字段名(用于引用值段、层级码段、首字母流水段)';
ALTER TABLE MDM_CODE_SEGMENT ADD COLUMN RELATED_SEGMENT_ID VARCHAR(32) DEFAULT NULL COMMENT '关联前段ID(用于段间关联，不同前缀使用独立流水序列)';

-- 编码记录表补充SEGMENT_ID列（如不存在）和PREFIX列唯一索引
ALTER TABLE MDM_CODE_RECORD ADD COLUMN SEGMENT_ID VARCHAR(32) DEFAULT NULL COMMENT '编码段ID';
ALTER TABLE MDM_CODE_RECORD ADD COLUMN PREFIX VARCHAR(255) DEFAULT '' COMMENT '流水号前缀(用于段间关联)';

-- 创建唯一索引保证并发安全
CREATE UNIQUE INDEX UK_CODE_RECORD ON MDM_CODE_RECORD (SCHEME_ID, SEGMENT_ID, PREFIX);
