CREATE DATABASE IF NOT EXISTS mdm_db DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE mdm_db;

CREATE TABLE IF NOT EXISTS BASE_USER (
    ID VARCHAR(20) NOT NULL PRIMARY KEY,
    USERNAME VARCHAR(60),
    PASSWORD VARCHAR(96),
    NICKNAME VARCHAR(60),
    ORGID VARCHAR(20),
    ORGNAME VARCHAR(270),
    STATUS VARCHAR(12),
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS BASE_ORG (
    ID VARCHAR(20) NOT NULL PRIMARY KEY,
    ORGNAME VARCHAR(270),
    PARENTID VARCHAR(20),
    STATUS VARCHAR(12),
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO BASE_ORG (ID, ORGNAME, PARENTID, STATUS) VALUES 
('ROOT', 'Group', NULL, '启用');

INSERT INTO BASE_USER (ID, USERNAME, PASSWORD, NICKNAME, ORGID, ORGNAME, STATUS) VALUES 
('admin', 'admin', 'admin', 'Admin', 'ROOT', 'Group', '启用');
