USE mdm_db;

CREATE TABLE BASE_USER (
    ID VARCHAR(20) NOT NULL PRIMARY KEY,
    USERNAME VARCHAR(60),
    PASSWORD VARCHAR(96),
    NICKNAME VARCHAR(60),
    SEX VARCHAR(36),
    ORGID VARCHAR(20),
    ORGNAME VARCHAR(270),
    BIRTHDAY DATE,
    EMAIL VARCHAR(120),
    PHONE VARCHAR(30),
    STATUS VARCHAR(12),
    SECURITY_LEVEL VARCHAR(36),
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE BASE_ORG (
    ID VARCHAR(20) NOT NULL PRIMARY KEY,
    ORGNAME VARCHAR(270),
    PARENTID VARCHAR(20),
    STATUS VARCHAR(12),
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE BASE_ROLE (
    ID VARCHAR(32) NOT NULL PRIMARY KEY,
    ROLE_CODE VARCHAR(30) NOT NULL UNIQUE,
    ROLE_NAME VARCHAR(60) NOT NULL UNIQUE,
    ORGID VARCHAR(20),
    STATUS VARCHAR(12),
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE BASE_GROUP (
    ID VARCHAR(32) NOT NULL PRIMARY KEY,
    GROUP_CODE VARCHAR(60) NOT NULL UNIQUE,
    GROUP_NAME VARCHAR(120) NOT NULL UNIQUE,
    ORGID VARCHAR(20),
    STATUS VARCHAR(12),
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE MDM_DATA_MODEL (
    ID VARCHAR(32) NOT NULL PRIMARY KEY,
    MODEL_CODE VARCHAR(60) NOT NULL UNIQUE,
    MODEL_NAME VARCHAR(120) NOT NULL,
    MODEL_TYPE VARCHAR(20),
    VERSION INT DEFAULT 1,
    STATUS VARCHAR(20),
    ORGID VARCHAR(20),
    DESCRIPTION TEXT,
    CREATE_BY VARCHAR(20),
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IS_DELETED TINYINT DEFAULT 0
);

CREATE TABLE MDM_MODEL_ATTRIBUTE (
    ID VARCHAR(32) NOT NULL PRIMARY KEY,
    MODEL_ID VARCHAR(32),
    ATTRIBUTE_CODE VARCHAR(60) NOT NULL,
    ATTRIBUTE_NAME VARCHAR(120) NOT NULL,
    DATA_TYPE VARCHAR(30),
    IS_REQUIRED TINYINT DEFAULT 0,
    MAX_LENGTH INT,
    DEFAULT_VALUE VARCHAR(255),
    DISPLAY_TYPE VARCHAR(20),
    SORT_ORDER INT DEFAULT 0,
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IS_DELETED TINYINT DEFAULT 0
);

CREATE TABLE MDM_MAIN_DATA (
    ID VARCHAR(32) NOT NULL PRIMARY KEY,
    MODEL_ID VARCHAR(32),
    CODE VARCHAR(60),
    VERSION INT DEFAULT 1,
    FLOW_STATUS VARCHAR(20),
    DATA_STATUS VARCHAR(20),
    JSON_DATA TEXT,
    CREATED_BY_ID VARCHAR(20),
    CREATED_BY_NAME VARCHAR(60),
    CREATED_BY_ORGID VARCHAR(20),
    SUBMITTED_BY_ORGID VARCHAR(20),
    MODIFIED_BY_ID VARCHAR(20),
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    MODIFY_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IS_MODIFY TINYINT DEFAULT 0,
    SECURITY_LEVEL VARCHAR(36),
    IS_DELETED TINYINT DEFAULT 0
);

CREATE TABLE MDM_WORKFLOW (
    ID VARCHAR(32) NOT NULL PRIMARY KEY,
    WORKFLOW_CODE VARCHAR(60) NOT NULL UNIQUE,
    WORKFLOW_NAME VARCHAR(120) NOT NULL,
    WORKFLOW_TYPE VARCHAR(20),
    ORGID VARCHAR(20),
    STATUS VARCHAR(12),
    DEFINITION TEXT,
    CREATE_BY VARCHAR(20),
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IS_DELETED TINYINT DEFAULT 0
);

INSERT INTO BASE_ORG (ID, ORGNAME, PARENTID, STATUS) VALUES
('ROOT', '集团总部', NULL, '启用'),
('ORG001', '研发中心', 'ROOT', '启用');

INSERT INTO BASE_USER (ID, USERNAME, PASSWORD, NICKNAME, ORGID, ORGNAME, STATUS) VALUES
('admin', 'admin', 'admin', '系统管理员', 'ROOT', '集团总部', '启用');

INSERT INTO MDM_DATA_MODEL (ID, MODEL_CODE, MODEL_NAME, MODEL_TYPE, VERSION, STATUS, ORGID, CREATE_BY, DESCRIPTION) VALUES
('model001', 'SUPPLIER', '供应商模型', '普通模型', 1, '已发布', 'ROOT', 'admin', '供应商主数据管理'),
('model002', 'CUSTOMER', '客户模型', '普通模型', 1, '已发布', 'ROOT', 'admin', '客户主数据管理');

INSERT INTO MDM_MAIN_DATA (ID, MODEL_ID, CODE, VERSION, FLOW_STATUS, DATA_STATUS, CREATED_BY_ID, CREATED_BY_NAME, CREATED_BY_ORGID) VALUES
('data001', 'model001', 'SUP202401001', 1, 'DONE', '审核通过', 'admin', '系统管理员', 'ROOT'),
('data002', 'model002', 'CUS202401001', 1, 'DONE', '审核通过', 'admin', '系统管理员', 'ROOT');

INSERT INTO MDM_WORKFLOW (ID, WORKFLOW_CODE, WORKFLOW_NAME, WORKFLOW_TYPE, ORGID, STATUS, CREATE_BY) VALUES
('wf001', 'WF_DEFAULT', '默认审核流程', '数据审核', 'ROOT', '启用', 'admin');
