-- 数据库更新脚本V3：归档表+主数据/模型字段扩展
USE mdm_db;

-- 归档申请表
CREATE TABLE IF NOT EXISTS MDM_ARCHIVE_APPLY (
    ID VARCHAR(32) NOT NULL PRIMARY KEY,
    MODEL_ID VARCHAR(32),
    MODEL_CODE VARCHAR(60),
    APPLY_USER_ID VARCHAR(20),
    APPLY_USER_NAME VARCHAR(60),
    APPLY_ORG_ID VARCHAR(20),
    ARCHIVE_REASON TEXT NOT NULL COMMENT '归档原因（必填）',
    STATUS VARCHAR(20) DEFAULT '待审核' COMMENT '待审核/已通过/已拒绝',
    REVIEWER_ID VARCHAR(20),
    REVIEW_OPINION TEXT,
    REVIEW_TIME DATETIME,
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MODEL_ID) REFERENCES MDM_DATA_MODEL(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 归档数据快照表
CREATE TABLE IF NOT EXISTS MDM_ARCHIVE_DATA (
    ID VARCHAR(32) NOT NULL PRIMARY KEY,
    APPLY_ID VARCHAR(32),
    DATA_ID VARCHAR(32),
    MODEL_CODE VARCHAR(60),
    DATA_CODE VARCHAR(60),
    DATA_CONTENT TEXT COMMENT '数据快照JSON',
    VERSION INT,
    ARCHIVE_TIME DATETIME,
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (APPLY_ID) REFERENCES MDM_ARCHIVE_APPLY(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 主数据表添加 SUBMIT_DESC 和 ARCHIVE_TIME 字段
SET @dbname = DATABASE();
SET @tablename = 'MDM_MAIN_DATA';

-- 添加 SUBMIT_DESC 列
SET @columnname = 'SUBMIT_DESC';
SET @preparedStatement = (SELECT IF(
  (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
   WHERE TABLE_SCHEMA = @dbname AND TABLE_NAME = @tablename AND COLUMN_NAME = @columnname) > 0,
  'SELECT 1',
  'ALTER TABLE MDM_MAIN_DATA ADD COLUMN SUBMIT_DESC TEXT AFTER IS_DELETED'
));
PREPARE alterIfNotExists FROM @preparedStatement;
EXECUTE alterIfNotExists;
DEALLOCATE PREPARE alterIfNotExists;

-- 添加 ARCHIVE_TIME 列
SET @columnname = 'ARCHIVE_TIME';
SET @preparedStatement = (SELECT IF(
  (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
   WHERE TABLE_SCHEMA = @dbname AND TABLE_NAME = @tablename AND COLUMN_NAME = @columnname) > 0,
  'SELECT 1',
  'ALTER TABLE MDM_MAIN_DATA ADD COLUMN ARCHIVE_TIME DATETIME AFTER SUBMIT_DESC'
));
PREPARE alterIfNotExists FROM @preparedStatement;
EXECUTE alterIfNotExists;
DEALLOCATE PREPARE alterIfNotExists;

-- 数据模型表添加 CODE_RULE_ID 和 WORKFLOW_ID 字段
SET @tablename = 'MDM_DATA_MODEL';

-- 添加 CODE_RULE_ID 列
SET @columnname = 'CODE_RULE_ID';
SET @preparedStatement = (SELECT IF(
  (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
   WHERE TABLE_SCHEMA = @dbname AND TABLE_NAME = @tablename AND COLUMN_NAME = @columnname) > 0,
  'SELECT 1',
  'ALTER TABLE MDM_DATA_MODEL ADD COLUMN CODE_RULE_ID VARCHAR(32) AFTER IS_DELETED'
));
PREPARE alterIfNotExists FROM @preparedStatement;
EXECUTE alterIfNotExists;
DEALLOCATE PREPARE alterIfNotExists;

-- 添加 WORKFLOW_ID 列
SET @columnname = 'WORKFLOW_ID';
SET @preparedStatement = (SELECT IF(
  (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
   WHERE TABLE_SCHEMA = @dbname AND TABLE_NAME = @tablename AND COLUMN_NAME = @columnname) > 0,
  'SELECT 1',
  'ALTER TABLE MDM_DATA_MODEL ADD COLUMN WORKFLOW_ID VARCHAR(32) AFTER CODE_RULE_ID'
));
PREPARE alterIfNotExists FROM @preparedStatement;
EXECUTE alterIfNotExists;
DEALLOCATE PREPARE alterIfNotExists;

-- 绑定供应商模型到编码规则和审核流程
UPDATE MDM_DATA_MODEL SET CODE_RULE_ID = 'rule001', WORKFLOW_ID = 'wf001' WHERE MODEL_CODE = 'SUPPLIER';
-- 绑定客户模型到编码规则和审核流程
UPDATE MDM_DATA_MODEL SET CODE_RULE_ID = 'rule002', WORKFLOW_ID = 'wf002' WHERE MODEL_CODE = 'CUSTOMER';
